camera.device.index=0
camera.width=1280
camera.height=720
camera.preview.width=880
camera.preview.height=505
camera.fps=30

gesture.pinch.on=0.08
gesture.pinch.off=0.11

ocr.language=eng
ocr.min.confidence=60
ocr.command=C:\\Program Files\\Tesseract-OCR\\tesseract.exe
